FROM node:24.2.0-alpine3.21

RUN adduser -D -s /bin/false app

ENV HOME=/home/app

COPY package*.json $HOME/shivam-traders-backend/

WORKDIR $HOME/shivam-traders-backend

RUN npm install

COPY . .

EXPOSE 3021

USER app

CMD ["npm", "start"]