

services:
  shivam-traders-backend:
    container_name: shivam-traders-backend
    build:
      context: .
      dockerfile: Dockerfile-pro
    environment:
      NODE_ENV: production
      PORT: 3021
    ports:
      - "3021:3021"
    restart: unless-stopped

# devlopment

# services:
#  shivam-traders-backend:
#    build:
#      context: .
#      dockerfile: Dockerfile-dev
#    environment:
#      NODE_ENV: development
#    ports:
#      - "3021:3021"
#    volumes:
#      - .:/home/app/shivam-traders-backend
#      - /home/app/shivam-traders-backend/node_modules
#    entrypoint: npm start
  

